In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd. read_csv("USA_Housing.csv")
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [4]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [7]:
x=df[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms', 'Area Population']]
y=df['Price']

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x

array([[ 1.02865969, -0.29692705,  0.02127433,  0.08806222, -1.31759867],
       [ 1.00080775,  0.02590164, -0.25550611, -0.72230146,  0.40399945],
       [-0.68462916, -0.11230283,  1.5162435 ,  0.93084045,  0.07240989],
       ...,
       [-0.48723454,  1.28447022, -2.17026949, -1.50025059, -0.29193658],
       [-0.05459152, -0.44669439,  0.14154061,  1.18205319,  0.65111608],
       [-0.28831272,  0.01521477, -0.19434166,  0.07185495,  1.04162464]])

In [9]:
x.shape

(5000, 5)

In [10]:
y.shape

(5000,)

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.9,random_state=1)

In [12]:
xtrain

array([[ 0.26510336,  0.59290884,  0.24342222,  1.80603322,  1.34004959],
       [ 0.55971647, -1.03958137,  0.00224141, -1.44352513,  1.21027191],
       [ 0.60596337,  0.47980601,  0.5158419 ,  0.91463317, -0.14412881],
       ...,
       [ 1.07239885,  0.47556361, -0.49568245, -1.20851967, -0.96599042],
       [ 0.4050464 , -0.76176576, -0.12605907,  0.18530586,  0.31715266],
       [-0.14321847, -0.76163631,  0.17472404,  1.02808409, -1.11125594]])

In [13]:
ytrain

3150    1.574280e+06
4633    1.268965e+06
1783    1.765281e+06
2541    1.499243e+06
2928    1.059431e+06
            ...     
2895    1.063206e+06
2763    8.732420e+05
905     1.345963e+06
3980    1.270928e+06
235     1.039107e+06
Name: Price, Length: 4500, dtype: float64

In [14]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [15]:
model.fit(xtrain,ytrain)

LinearRegression()

In [16]:
col= ['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms', 'Area Population']
coeff_df = pd.DataFrame(model.coef_,col,columns=['M'])
coeff_df['c']=model.intercept_
coeff_df

M             c
Avg. Area Income              231052.346247  1.232648e+06
Avg. Area House Age           164060.773152  1.232648e+06
Avg. Area Number of Rooms     121506.115970  1.232648e+06
Avg. Area Number of Bedrooms    1519.027261  1.232648e+06
Area Population               150961.351855  1.232648e+06

In [17]:
ypred=model.predict(xtest)
ypred

array([1554683.5214399 , 1583563.24439528,  941225.74026093,
        943645.05050714, 1182422.13103409,  328801.82154785,
       1927836.21341998, 1069153.56034445, 1650471.09661947,
       1073173.73634535,  625424.71460166, 1538374.13036006,
       1631652.9247289 , 1052427.98639216,  959014.31519697,
       1234206.9702727 , 1429305.22944777,  925549.79891021,
       1126241.93729671, 1159272.38021256, 1295981.01672271,
       1864678.19351198, 1182431.10145894, 1191493.57355746,
       1557481.81254847, 1862564.76945657,  813324.88451243,
       1063060.65771745, 1226156.79626916,  659278.7795202 ,
        841633.35073089, 1635760.74010405,  664805.32190952,
       1117024.80078667,  799534.550374  , 1303687.59142732,
       1147113.45373281, 1348569.86939243, 1033860.534031  ,
       1162323.80837825, 1413268.53943701, 1308874.97935079,
       1578249.18647836, 1300199.87406542,  846787.67223351,
        923146.16088842, 1230070.83185333, 1161447.51667952,
       1422509.2038584 ,

In [18]:
ytest.values

array([1413579.81675087, 1618721.13842984,  841392.49302811,
        881443.92472646, 1174747.55058413,  266298.88111836,
       1877941.97142307, 1022408.90104638, 1766248.40325248,
        949072.24959546,  565937.20055318, 1437153.95853193,
       1582605.53510266, 1009854.70493643, 1116351.75343858,
       1255736.40858762, 1504441.01015029,  837540.16974077,
       1096069.28687736, 1205962.99495335, 1130844.02936265,
       1815920.44980542, 1023595.11287068, 1054304.1717288 ,
       1399909.04869688, 1710612.02954514,  670063.0223057 ,
       1245785.05095909, 1168760.42768571,  412269.20339956,
        677988.25546768, 1715435.99111606,  662630.34394019,
       1167449.98986973,  714706.42885374, 1411217.49285109,
       1200125.44711925, 1322439.10755647, 1127637.5573666 ,
       1066040.78865733, 1383842.1850596 , 1364306.768681  ,
       1682105.84747145, 1380602.55558134,  880084.70044787,
        779207.55461309, 1029861.62290085, 1106149.68565739,
       1327806.72883192,

In [19]:
from sklearn.metrics import r2_score
r2=r2_score(ytest,ypred)
r2

0.9168251003129223